# Generated by Django 3.2.4 on 2021-06-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_students_course_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professors',
            old_name='title_id',
            new_name='titles',
        ),
    ]
